# Generated by Django 5.1.6 on 2025-03-19 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='musicmodel',
            table='musics',
        ),
    ]
