# Generated by Django 5.1.6 on 2025-04-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albummodel',
            name='genre_id',
        ),
        migrations.AddField(
            model_name='generemodel',
            name='album_id',
            field=models.ManyToManyField(null=True, to='musicapp.albummodel'),
        ),
        migrations.AlterField(
            model_name='generemodel',
            name='artist_id',
            field=models.ManyToManyField(null=True, to='musicapp.ArtistsModel'),
        ),
        migrations.AlterField(
            model_name='generemodel',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='generemodel',
            name='music_id',
            field=models.ManyToManyField(null=True, to='musicapp.musicmodel'),
        ),
        migrations.AlterModelTable(
            name='generemodel',
            table='generes',
        ),
    ]
