# Generated by Django 5.1.6 on 2025-03-20 19:49

import core_apps.musicapp.models.musics
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_alter_musicmodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicmodel',
            name='musiccover',
            field=models.ImageField(null=True, upload_to=core_apps.musicapp.models.musics.music_file_cover),
        ),
    ]
