# Generated by Django 5.1.6 on 2025-04-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_remove_albummodel_genre_id_generemodel_album_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generemodel',
            name='album_id',
            field=models.ManyToManyField(blank=True, to='musicapp.albummodel'),
        ),
        migrations.AlterField(
            model_name='generemodel',
            name='artist_id',
            field=models.ManyToManyField(blank=True, to='musicapp.ArtistsModel'),
        ),
        migrations.AlterField(
            model_name='generemodel',
            name='music_id',
            field=models.ManyToManyField(blank=True, to='musicapp.musicmodel'),
        ),
    ]
