# Generated by Django 5.1.6 on 2025-05-03 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_alter_generemodel_album_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artistsmodel',
            options={'verbose_name': 'Artist'},
        ),
    ]
