# Generated by Django 5.1.6 on 2025-03-20 20:05

import core_apps.musicapp.models.musics
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_alter_musicmodel_musiccover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicmodel',
            name='musiccover',
            field=models.ImageField(default=1, upload_to=core_apps.musicapp.models.musics.music_file_cover),
            preserve_default=False,
        ),
    ]
