# Generated by Django 5.1.6 on 2025-05-10 15:58

import core_apps.musicapp.models.playlists
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_alter_artistsmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlistmodel',
            options={'ordering': ['-title'], 'verbose_name': 'playlist'},
        ),
        migrations.RemoveField(
            model_name='playlistmodel',
            name='playlistcover',
        ),
        migrations.AddField(
            model_name='playlistmodel',
            name='cover',
            field=models.FileField(default=1, upload_to=core_apps.musicapp.models.playlists.playlist_file_cover, verbose_name='Playlist cover'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlistmodel',
            name='public_playlist',
            field=models.SmallIntegerField(default=0, verbose_name='Public Playlist'),
        ),
        migrations.AlterField(
            model_name='playlistmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creatation datetime'),
        ),
        migrations.AlterField(
            model_name='playlistmodel',
            name='description',
            field=models.CharField(max_length=256, null=True, verbose_name='playlist description'),
        ),
        migrations.AlterField(
            model_name='playlistmodel',
            name='music_id',
            field=models.ManyToManyField(blank=True, to='musicapp.musicmodel', verbose_name='Musics'),
        ),
        migrations.AlterField(
            model_name='playlistmodel',
            name='title',
            field=models.CharField(max_length=32, verbose_name='Playlist title'),
        ),
        migrations.AlterField(
            model_name='playlistmodel',
            name='totaltracks',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Playlist tracks count'),
        ),
        migrations.AlterField(
            model_name='playlistmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modification'),
        ),
    ]
