# Generated by Django 5.1.6 on 2025-05-12 18:11

import core_apps.musicapp.models.playlists
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0005_alter_playlistmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generemodel',
            name='music_id',
            field=models.ManyToManyField(blank=True, related_name='genere_id', to='musicapp.musicmodel'),
        ),
        migrations.AlterField(
            model_name='playlistmodel',
            name='cover',
            field=models.FileField(blank=True, upload_to=core_apps.musicapp.models.playlists.playlist_file_cover, verbose_name='Playlist cover'),
        ),
        migrations.AlterField(
            model_name='playlistmodel',
            name='music_id',
            field=models.ManyToManyField(blank=True, related_name='music_id', to='musicapp.musicmodel', verbose_name='Musics'),
        ),
    ]
