# Generated by Django 5.1.6 on 2025-05-12 18:15

import core_apps.musicapp.models.playlists
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0006_alter_generemodel_music_id_alter_playlistmodel_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistmodel',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to=core_apps.musicapp.models.playlists.playlist_file_cover, verbose_name='Playlist cover'),
        ),
    ]
