# Generated by Django 5.1.6 on 2025-04-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0006_alter_musicmodel_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albummodel',
            name='genre_id',
            field=models.ManyToManyField(blank=True, null=True, to='musicapp.generemodel'),
        ),
        migrations.AlterField(
            model_name='albummodel',
            name='music_id',
            field=models.ManyToManyField(blank=True, null=True, to='musicapp.musicmodel'),
        ),
        migrations.AlterField(
            model_name='albummodel',
            name='totaltracks',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='albummodel',
            table='albums',
        ),
    ]
