# Generated by Django 5.1.6 on 2025-04-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0007_alter_albummodel_genre_id_alter_albummodel_music_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albummodel',
            name='artist_id',
            field=models.ManyToManyField(blank=True, to='musicapp.artistsmodels'),
        ),
        migrations.AlterField(
            model_name='albummodel',
            name='genre_id',
            field=models.ManyToManyField(blank=True, to='musicapp.generemodel'),
        ),
        migrations.AlterField(
            model_name='albummodel',
            name='music_id',
            field=models.ManyToManyField(blank=True, to='musicapp.musicmodel'),
        ),
    ]
