# Generated by Django 5.1.6 on 2025-05-15 18:16

import core_apps.musicapp.models.musics
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0007_alter_playlistmodel_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musicmodel',
            options={'ordering': ['-title'], 'verbose_name': 'music'},
        ),
        migrations.AlterField(
            model_name='musicmodel',
            name='artist_id',
            field=models.ManyToManyField(related_name='artist_id', to='musicapp.artistsmodel', verbose_name='Artists'),
        ),
        migrations.AlterField(
            model_name='musicmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creatation datetime'),
        ),
        migrations.AlterField(
            model_name='musicmodel',
            name='duration',
            field=models.CharField(max_length=32, null=True, verbose_name='Music duration'),
        ),
        migrations.AlterField(
            model_name='musicmodel',
            name='lyrics',
            field=models.TextField(null=True, verbose_name='Music lyrics'),
        ),
        migrations.AlterField(
            model_name='musicmodel',
            name='musiccover',
            field=models.ImageField(upload_to=core_apps.musicapp.models.musics.music_file_cover, verbose_name='Music cover'),
        ),
        migrations.AlterField(
            model_name='musicmodel',
            name='musicfile',
            field=models.FileField(upload_to=core_apps.musicapp.models.musics.music_file_cover, verbose_name='Music file'),
        ),
        migrations.AlterField(
            model_name='musicmodel',
            name='title',
            field=models.CharField(max_length=32, verbose_name='Music title'),
        ),
        migrations.AlterField(
            model_name='musicmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modification'),
        ),
    ]
