# Generated by Django 5.1.6 on 2025-05-15 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0008_alter_musicmodel_options_alter_musicmodel_artist_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicmodel',
            old_name='musiccover',
            new_name='cover',
        ),
        migrations.RenameField(
            model_name='musicmodel',
            old_name='musicfile',
            new_name='file',
        ),
    ]
