# Generated by Django 5.1.6 on 2025-05-18 19:37

import core_apps.musicapp.models.genres
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0009_rename_musiccover_musicmodel_cover_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generemodel',
            options={'ordering': ['-name'], 'verbose_name': 'Genere'},
        ),
        migrations.AlterModelOptions(
            name='musicmodel',
            options={'ordering': ['-title'], 'verbose_name': 'Music'},
        ),
        migrations.RemoveField(
            model_name='generemodel',
            name='generecover',
        ),
        migrations.AddField(
            model_name='generemodel',
            name='cover',
            field=models.FileField(default=1, upload_to=core_apps.musicapp.models.genres.genere_file_cover, verbose_name='Genere cover'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='generemodel',
            name='album_id',
            field=models.ManyToManyField(blank=True, related_name='genere_album', to='musicapp.albummodel', verbose_name='Albums'),
        ),
        migrations.AlterField(
            model_name='generemodel',
            name='artist_id',
            field=models.ManyToManyField(blank=True, related_name='gerene_artists', to='musicapp.artistsmodel', verbose_name='Artists'),
        ),
        migrations.AlterField(
            model_name='generemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creatation datetime'),
        ),
        migrations.AlterField(
            model_name='generemodel',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Genere description'),
        ),
        migrations.AlterField(
            model_name='generemodel',
            name='music_id',
            field=models.ManyToManyField(blank=True, related_name='genere_musics', to='musicapp.musicmodel', verbose_name='Musics'),
        ),
        migrations.AlterField(
            model_name='generemodel',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Genere name'),
        ),
        migrations.AlterField(
            model_name='generemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modification'),
        ),
    ]
