# Generated by Django 5.1.6 on 2025-05-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0010_alter_generemodel_options_alter_musicmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generemodel',
            name='playlist_id',
            field=models.ManyToManyField(blank=True, related_name='genere_playlists', to='musicapp.playlistmodel', verbose_name='Playlists'),
        ),
        migrations.AlterField(
            model_name='generemodel',
            name='album_id',
            field=models.ManyToManyField(blank=True, related_name='genere_albums', to='musicapp.albummodel', verbose_name='Albums'),
        ),
    ]
