# Generated by Django 5.1.6 on 2025-05-19 22:58

import core_apps.musicapp.models.albums
import core_apps.musicapp.models.artists
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0011_generemodel_playlist_id_alter_generemodel_album_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artistsmodel',
            options={'ordering': ['-name'], 'verbose_name': 'Artist'},
        ),
        migrations.AlterField(
            model_name='albummodel',
            name='created_at',
            field=models.BigIntegerField(default=core_apps.musicapp.models.albums.nowTimeStamp),
        ),
        migrations.AlterField(
            model_name='albummodel',
            name='updated_at',
            field=models.BigIntegerField(default=core_apps.musicapp.models.albums.nowTimeStamp),
        ),
        migrations.AlterField(
            model_name='artistsmodel',
            name='bio',
            field=models.CharField(max_length=256, null=True, verbose_name='Artist bio'),
        ),
        migrations.AlterField(
            model_name='artistsmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creatation datetime'),
        ),
        migrations.AlterField(
            model_name='artistsmodel',
            name='image',
            field=models.ImageField(upload_to=core_apps.musicapp.models.artists.artists_direcrory, verbose_name='Artist image'),
        ),
        migrations.AlterField(
            model_name='artistsmodel',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Artist name'),
        ),
        migrations.AlterField(
            model_name='artistsmodel',
            name='realname',
            field=models.CharField(max_length=64, null=True, verbose_name='Artist realname'),
        ),
        migrations.AlterField(
            model_name='artistsmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modification'),
        ),
    ]
