# Generated by Django 5.1.6 on 2025-05-21 19:56

import core_apps.musicapp.models.albums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0012_alter_artistsmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albummodel',
            options={'ordering': ['-title'], 'verbose_name': 'Albums'},
        ),
        migrations.RemoveField(
            model_name='albummodel',
            name='albumcover',
        ),
        migrations.AddField(
            model_name='albummodel',
            name='cover',
            field=models.FileField(default=1, upload_to=core_apps.musicapp.models.albums.album_file_cover, verbose_name='Album cover'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='albummodel',
            name='artist_id',
            field=models.ManyToManyField(blank=True, to='musicapp.artistsmodel', verbose_name='Artists ablbum'),
        ),
        migrations.AlterField(
            model_name='albummodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creatation datetime'),
        ),
        migrations.AlterField(
            model_name='albummodel',
            name='description',
            field=models.CharField(max_length=256, null=True, verbose_name='Album description'),
        ),
        migrations.AlterField(
            model_name='albummodel',
            name='music_id',
            field=models.ManyToManyField(blank=True, to='musicapp.musicmodel', verbose_name='Musics ablbum'),
        ),
        migrations.AlterField(
            model_name='albummodel',
            name='title',
            field=models.CharField(max_length=32, verbose_name='Album title'),
        ),
        migrations.AlterField(
            model_name='albummodel',
            name='totaltracks',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Ablum totaltracks'),
        ),
        migrations.AlterField(
            model_name='albummodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modification'),
        ),
    ]
