# Generated by Django 5.1.6 on 2025-04-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0008_alter_albummodel_artist_id_alter_albummodel_genre_id_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='playlists',
            field=models.ManyToManyField(blank=True, to='musicapp.albummodel'),
        ),
    ]
