# Generated by Django 5.1.6 on 2025-04-23 17:37

import core_apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile',
            field=models.FileField(blank=True, upload_to=core_apps.user.models.profile_file_cover),
        ),
    ]
