# Generated by Django 5.1.6 on 2025-04-24 16:46

import core_apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_users_playlists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile',
            field=models.ImageField(blank=True, upload_to=core_apps.user.models.profile_file_cover),
        ),
    ]
