# Generated by Django 5.1.6 on 2025-05-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_users_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='resest_password',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
