# Generated by Django 5.1.6 on 2025-05-04 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_users_resest_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='resest_password',
            new_name='reset_password',
        ),
    ]
