# Generated by Django 5.1.6 on 2025-05-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_resest_password_users_reset_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('locked', 'Locked')], default='active', max_length=8),
        ),
        migrations.AddField(
            model_name='users',
            name='reset_password_attempt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='reset_password_expire_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
