# Generated by Django 5.1.6 on 2025-05-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_users_options_alter_users_account_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='otp',
            field=models.CharField(max_length=6, null=True, verbose_name='One time password'),
        ),
        migrations.AddField(
            model_name='users',
            name='otp_attempt',
            field=models.IntegerField(default=0, verbose_name='One time password attempt'),
        ),
        migrations.AddField(
            model_name='users',
            name='otp_expire_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='One time password expiration'),
        ),
        migrations.AlterField(
            model_name='users',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive'), ('locked', 'Locked')], default='deactive', max_length=8, verbose_name='Account status'),
        ),
    ]
