# Generated by Django 5.1.6 on 2025-05-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_users_otp_users_otp_attempt_users_otp_expire_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=0, verbose_name='Account activation'),
        ),
    ]
