# Generated by Django 5.1.6 on 2025-05-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0005_alter_playlistmodel_options_and_more'),
        ('user', '0010_alter_users_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creatation datetime'),
        ),
        migrations.AlterField(
            model_name='users',
            name='playlists',
            field=models.ManyToManyField(blank=True, related_name='playlists_users', to='musicapp.playlistmodel', verbose_name='Playlists'),
        ),
        migrations.AlterField(
            model_name='users',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modification'),
        ),
    ]
