# Generated by Django 5.1.6 on 2025-05-15 18:01

import core_apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_users_created_at_alter_users_playlists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile',
            field=models.ImageField(null=True, upload_to=core_apps.user.models.profile_file_cover, verbose_name='User profile'),
        ),
    ]
